### ISSUE TITLE
webhook response status 400 bad request

### ISSUE THREAD

**Issue by ricklagerweij** [gmauleon/alertmanager-zabbix-webhook#1]
Hi @gmauleon,

Currently configuring the alert from prometheus to the webhook but I'm getting a 400 bad request.

Alertmanager logs;
level=debug ts=2018-09-20T11:53:57.096317774Z caller=notify.go:668 component=dispatcher msg="Notify attempt failed" attempt=1 integration=webhook receiver=zabbix err="unexpected status code 400 from http://10.72.52.106:8080/alerts"

Is the zabbix-alertmanager-webnhook still working properly with the latest alertmanager?

**Comment by ricklagerweij** [comment]
@gmauleon missing some of the json formats e..g.

{
  "version": "4",
  "groupKey": <string>,    // key identifying the group of alerts (e.g. to deduplicate)
  "status": "<resolved|firing>",
  "receiver": <string>,
  "groupLabels": <object>,
  "commonLabels": <object>,
  "commonAnnotations": <object>,
  "externalURL": <string>,  // backlink to the Alertmanager.
  "alerts": [
    {
      **"status": "<resolved|firing>",**
      "labels": <object>,
      "annotations": <object>,
      "startsAt": "<rfc3339>",
      "endsAt": "<rfc3339>",
      **"generatorURL": <string> // identifies the entity that caused the alert**
    },
    ...
  ]
}

**Comment by gmauleon** [comment]
Thanks for the heads-up, I'll try to have a look later this week

**Comment by ricklagerweij** [comment]
@gmauleon we fixed it, works in my fork thanks anyway;)

**Comment by gmauleon** [comment]
Hum actually I think you probably got lucky there, I don't think the missing fields are the problem.
It's the way I was handling alerts as a group only instead of individual alerts which is completely wrong :)

I bet if you fire up multiple alerts at the same time you'll have the problem again.

**Comment by gmauleon** [comment]
@ricklagerweij if you ever have time, try out the last release, should handle multi alerts the way it always should have.

**Comment by ricklagerweij** [comment]
Awesome @gmauleon! We did indeed get issues by sending multiple alerts, solved by your latest commit :)

Currently the alertmanager only sends data to the webhook when a trigger hits it threshold, how would it be possible in any way to send a 0 value to zabbix when no data is send from alertmanager?

**Comment by gmauleon** [comment]
Hum, I don't think it's really the job of an alertmanager webhook though, it's purpose is only to forward alerts to whatever backend it supports.
You could handle that case direcly at the source, like having different rules for when Prometheus can't scrap a target or when there is absent data there and have a different item in Zabbix for those.

**Comment by pauloeliasjr** [comment]
Hi @gmauleon 

I'm still getting 400 when trying to test the webhook. I'm using it on kubernetes (latest image tag). 
Could you please give me some directions to get it working?

**Comment by gmauleon** [comment]
Hi there,
Sorry I'm not looking much at this project anymore those days.
I`ll try to have a look with the latest alertmanager somewhere this week, see if there is a quick win.

**Comment by gmauleon** [comment]
Hey @pauloeliasjr,

Just gave it a try with the latest alertmanager and I don't see any problems.
Do you have more context for your 400?
Any logs from the webhook?
The configuration you are using might help too.

Thanks
Gael
